type Query {
  getCurrentUser: User
}

type Mutation {
  signupUser(username: String!, email: String!, password: String!): Token
  signinUser(username: String!, password: String!): Token
}

type User {
  _id: ID
  username: String!
  email: String!
  password: String!
  joinDate: String
  playerCharacters: [PlayerCharacter]
}

type Token {
  token: String!
}

# game-related queries:

extend type Query {
  playerCharacters: [PlayerCharacter]
}

# game-related mutations:

extend type Mutation {
  createPlayerCharacter(name: String!): PlayerCharacter
  overrideAbilityScore(playerCharacterId: ID!, abilityScoreName: AbilityScoreName!, value: Int!): PlayerCharacter
  overrideSkill(playerCharacterId: ID!, skillName: SkillName!, value: Int!): PlayerCharacter
}

# game-related reference types:

type AbilityScore {
  id: ID!
  name: AbilityScoreName!
  fullName: String!
  description: String!
  skills: [Skill!]!
}

type Skill {
  id: ID!
  name: SkillName!
  description: String!
  abilityScore: [AbilityScore!]!
}

# game-related entity types:

type PlayerCharacter {
  name: String!
  abilityScores: [AbilityScoreValue!]!
  skills: [SkillValue!]!
  id: ID!
  createdBy: User!
}

type AbilityScoreValue {
  name: AbilityScoreName!
  value: Int!
  proficient: Boolean!
  abilityScore: AbilityScore!
  bonusSources: [BonusSource]!
}

type SkillValue {
  name: SkillName!
  value: Int!
  proficient: Boolean!
  skill: Skill!
  bonusSources: [BonusSource]!
}

type BonusSource {
  explanation: String!
}

# game-related enums:

enum AbilityScoreName {
  STR
  DEX
  CON
  INT
  WIS
  CHA
}

enum SkillName {
  ACROBATICS
  ANIMAL_HANDLING
  ARCANA
  ATHLETICS
  DECEPTION
  HISTORY
  INSIGHT
  INTIMIDATION
  INVESTIGATION
  MEDICINE
  NATURE
  PERCEPTION
  PERFORMANCE
  PERSUASION
  RELIGION
  SLEIGHT_OF_HAND
  STEALTH
  SURVIVAL
}