type User {
  _id: ID
  # username: String! @unique
  username: String!
  email: String!
  password: String!
  joinDate: String
}

type Query {
  getUser: User
}

type Mutation {
  signupUser(username: String!, email: String!, password: String!): User
}